version: '2.0'
services:
  web:
    build: .
    ports:
    - "3000:3000"
    environment:
    - MONGO_URL='mongodb://mongo:27017/test'
    depends_on:
    - mongo
  mongo:
    image: mongo
    ports:
    - "27017:27017"